- name: Converge all hosts
  hosts: all
  roles:
    - role: "{{ playbook_dir|dirname|dirname }}"
      vars:
        groupware_server_tls_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
        groupware_server_tls_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
        groupware_server_accounts:
          - email: user1@domain.test
            password: test1
            email_aliases:
              - postmaster@domain.test
              - abuse@domain.test
              - user@alias.test
            sieve_script: test

          - email: user2@domain.test
            password: test2
